
const cursos = [
  { valor: "Administração", label: "Administração", campus: "Salvador" },
  { valor: "Administração pública", label: "Administração pública", campus: "Salvador" },
  { valor: "Administração pública e gestão social", label: "Administração pública e gestão social", campus: "Salvador" },
  { valor: "Arquitetura e urbanismo", label: "Arquitetura e urbanismo", campus: "Salvador" },
  { valor: "Arquivologia", label: "Arquivologia", campus: "Salvador" },
  { valor: "Artes cênicas - direção teatral", label: "Artes cênicas - direção teatral", campus: "Salvador" },
  { valor: "Artes cênicas - interpretação teatral", label: "Artes cênicas - interpretação teatral", campus: "Salvador" },
  { valor: "Artes visuais", label: "Artes visuais", campus: "Salvador" },
  { valor: "Biblioteconomia", label: "Biblioteconomia", campus: "Salvador" },
  { valor: "Biblioteconomia e documentação", label: "Biblioteconomia e documentação", campus: "Salvador" },
  { valor: "Biotecnologia", label: "Biotecnologia", campus: "Salvador" },
  { valor: "Canto lírico", label: "Canto lírico", campus: "Salvador" },
  { valor: "Ciência da computação", label: "Ciência da computação", campus: "Salvador" },
  { valor: "Ciências biológicas", label: "Ciências biológicas", campus: "Salvador" },
  { valor: "Ciências contábeis", label: "Ciências contábeis", campus: "Salvador" },
  { valor: "Ciências econômicas", label: "Ciências econômicas", campus: "Salvador" },
  { valor: "Ciências naturais", label: "Ciências naturais", campus: "Salvador" },
  { valor: "Ciências sociais", label: "Ciências sociais", campus: "Salvador" },
  { valor: "Composição e regência - composição - composição", label: "Composição e regência - composição - composição", campus: "Salvador" },
  { valor: "Computação", label: "Computação", campus: "Salvador" },
  { valor: "Comunicação - produção em comunicação e cultura - produção em comunicação e cultura", label: "Comunicação - produção em comunicação e cultura - produção em comunicação e cultura", campus: "Salvador" },
  { valor: "Dança", label: "Dança", campus: "Salvador" },
  { valor: "Desenho e plástica", label: "Desenho e plástica", campus: "Salvador" },
  { valor: "Design - programação visual", label: "Design - programação visual", campus: "Salvador" },
  { valor: "Design de interiores", label: "Design de interiores", campus: "Salvador" },
  { valor: "Direito", label: "Direito", campus: "Salvador" },
  { valor: "Educação do campo - ciências da natureza", label: "Educação do campo - ciências da natureza", campus: "Salvador" },
  { valor: "Educação física", label: "Educação física", campus: "Salvador" },
  { valor: "Educação intercultural indígena - humanidades", label: "Educação intercultural indígena - humanidades", campus: "Salvador" },
  { valor: "Enfermagem", label: "Enfermagem", campus: "Salvador" },
  { valor: "Engenharia civil", label: "Engenharia civil", campus: "Salvador" },
  { valor: "Engenharia da computação", label: "Engenharia da computação", campus: "Salvador" },
  { valor: "Engenharia de agrimensura e cartográfica", label: "Engenharia de agrimensura e cartográfica", campus: "Salvador" },
  { valor: "Engenharia de controle e automação de processos", label: "Engenharia de controle e automação de processos", campus: "Salvador" },
  { valor: "Engenharia de minas", label: "Engenharia de minas", campus: "Salvador" },
  { valor: "Engenharia de petróleo", label: "Engenharia de petróleo", campus: "Salvador" },
  { valor: "Engenharia de produção", label: "Engenharia de produção", campus: "Camaçari" },
  { valor: "Engenharia de transportes", label: "Engenharia de transportes", campus: "Salvador" },
  { valor: "Engenharia elétrica", label: "Engenharia elétrica", campus: "Camaçari" },
  { valor: "Engenharia mecânica", label: "Engenharia mecânica", campus: "Salvador" },
  { valor: "Engenharia química", label: "Engenharia química", campus: "Salvador" },
  { valor: "Engenharia sanitária e ambiental", label: "Engenharia sanitária e ambiental", campus: "Salvador" },
  { valor: "Estatística", label: "Estatística", campus: "Salvador" },
  { valor: "Estudos de gênero e diversidade", label: "Estudos de gênero e diversidade", campus: "Salvador" },
  { valor: "Farmácia", label: "Farmácia", campus: "Salvador" },
  { valor: "Filosofia", label: "Filosofia", campus: "Salvador" },
  { valor: "Física", label: "Física", campus: "Salvador" },
  { valor: "Fisioterapia", label: "Fisioterapia", campus: "Salvador" },
  { valor: "Fonoaudiologia", label: "Fonoaudiologia", campus: "Salvador" },
  { valor: "Gastronomia", label: "Gastronomia", campus: "Salvador" },
  { valor: "Geofísica", label: "Geofísica", campus: "Salvador" },
  { valor: "Geografia", label: "Geografia", campus: "Salvador" },
  { valor: "Geologia", label: "Geologia", campus: "Salvador" },
  { valor: "Gestão do turismo e desenvolvimento sustentável", label: "Gestão do turismo e desenvolvimento sustentável", campus: "Salvador" },
  { valor: "História", label: "História", campus: "Salvador" },
  { valor: "Instrumento - violão", label: "Instrumento - violão", campus: "Salvador" },
  { valor: "Interdisciplinar em artes", label: "Interdisciplinar em artes", campus: "Salvador" },
  { valor: "Interdisciplinar em ciência e tecnologia", label: "Interdisciplinar em ciência e tecnologia", campus: "Salvador" },
  { valor: "Interdisciplinar em ciência, tecnologia e inovação", label: "Interdisciplinar em ciência, tecnologia e inovação", campus: "Camaçari" },
  { valor: "Interdisciplinar em humanidades", label: "Interdisciplinar em humanidades", campus: "Salvador" },
  { valor: "Interdisciplinar em saúde", label: "Interdisciplinar em saúde", campus: "Salvador" },
  { valor: "Jornalismo", label: "Jornalismo", campus: "Salvador" },
  { valor: "Letras - língua estrangeira moderna ou clássica - inglês", label: "Letras - língua estrangeira moderna ou clássica - inglês", campus: "Salvador" },
  { valor: "Letras vernáculas - português", label: "Letras vernáculas - português", campus: "Salvador" },
  { valor: "Letras vernáculas com língua estrangeira moderna - inglês", label: "Letras vernáculas com língua estrangeira moderna - inglês", campus: "Salvador" },
  { valor: "Matemática", label: "Matemática", campus: "Salvador" },
  { valor: "Medicina", label: "Medicina", campus: "Salvador" },
  { valor: "Medicina veterinária", label: "Medicina veterinária", campus: "Salvador" },
  { valor: "Museologia", label: "Museologia", campus: "Salvador" },
  { valor: "Música", label: "Música", campus: "Salvador" },
  { valor: "Música popular", label: "Música popular", campus: "Salvador" },
  { valor: "Nutrição", label: "Nutrição", campus: "Salvador" },
  { valor: "Oceanografia", label: "Oceanografia", campus: "Salvador" },
  { valor: "Odontologia", label: "Odontologia", campus: "Salvador" },
  { valor: "Pedagogia", label: "Pedagogia", campus: "Salvador" },
  { valor: "Psicologia - formação de psicólogo", label: "Psicologia - formação de psicólogo", campus: "Salvador" },
  { valor: "Química", label: "Química", campus: "Salvador" },
  { valor: "Saúde coletiva", label: "Saúde coletiva", campus: "Salvador" },
  { valor: "Secretariado executivo", label: "Secretariado executivo", campus: "Salvador" },
  { valor: "Segurança pública", label: "Segurança pública", campus: "Salvador" },
  { valor: "Serviço social", label: "Serviço social", campus: "Salvador" },
  { valor: "Sistemas de informação", label: "Sistemas de informação", campus: "Salvador" },
  { valor: "Teatro", label: "Teatro", campus: "Salvador" },
  { valor: "Terapia ocupacional", label: "Terapia ocupacional", campus: "Salvador" },
  { valor: "Zootecnia", label: "Zootecnia", campus: "Salvador" },
];


 export const campus = [
    { valor: "Salvador", label: "Salvador" },
    { valor: "Vitória da Conquista", label: "Vitória da Conquista" },
  ];
